@url = localhost:8888

POST /auth/register HTTP/1.1
Host: {{url}}
Content-Type: application/json

{
    "email": "BARUNICH@gmail.com",
    "password": "hsadfa"
}

###
POST /auth/login HTTP/1.1
Host: {{url}}
Content-Type: application/json

{
    "email": "BARUNICH@gmail.com",
    "password": "hsadfa"
}

###
GET /admin/users HTTP/1.1
Host: {{url}}

###
GET /admin/users/test/test@gmail.com HTTP/1.1
Host: {{url}}
###
GET /admin/users/1 HTTP/1.1
Host: {{url}}

###
POST /admin/users HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "BARUNICH@gmail.com",
    "password": "hsadfa"
}

###
PATCH /users/10 HTTP/1.1
Host: localhost:8888
Content-Type: application/json

{
    "email": "berubah@gmail.com",
    "password": "jkasdbva"
}

###
DELETE  /users/10 HTTP/1.1
Host: localhost:8888

